### ISSUE TITLE
customization

### ISSUE THREAD

**Issue by podhmo** [podhmo/swagger-marshmallow-codegen#1]

**Comment by podhmo** [comment]
- overiding base schema class
- adding type-format
- adding custom hook

**Comment by podhmo** [comment]
## overriding base schema class

```python
class MySchema(Schema):
    class Meta:
        ordered = True
        strict = True
```

Using Custom Schema class instead of `marshmallow.Schema`

**Comment by podhmo** [comment]
## adding type-format

```yaml
definitions:
  person:
    properties:
      id:
        type: string
        format: objectId
      name:
        type: string
```

then , treating a property `type, format = "string", "objectId"` as `bson.ObjectId`
