### ISSUE TITLE
nesting array type fields's options are ignored

### ISSUE THREAD

**Issue by podhmo** [podhmo/swagger-marshmallow-codegen#10]
```yaml
definitions:
  xs:
    type: array
    items:
      type: string
      enum:
      - x
      - y
      - z
  member:
    type: object
    properties:
      name:
        type: string
      color:
        type: string
        enum:
          - r
          - g
          - b
      xs:
        type: array
        items:
          type: string
          enum:
          - x
          - y
          - z
```

currently

```python
# -*- coding:utf-8 -*-
from marshmallow import (
    Schema,
    fields
)
from marshmallow.validate import OneOf


class Member(Schema):
    name = fields.String()
    color = fields.String(validate=[OneOf(choices=['r', 'g', 'b'], labels=[])])
    xs = fields.List(fields.String())
```
