### ISSUE TITLE
careless schema definitions (memo)

### ISSUE THREAD

**Issue by podhmo** [podhmo/swagger-marshmallow-codegen#59]

**Comment by podhmo** [comment]
```yaml
definitions:
  person:
    properties:
      name:
        type: string
     age:
        type: integer
    required:
      -name # not - name
```
