### ISSUE TITLE
treating AdditionalProperties only schema as Dict field

### ISSUE THREAD

**Issue by podhmo** [podhmo/swagger-marshmallow-codegen#64]
```yaml
definitions:
  person:
    type: object
    properties:
      name:
        type: string
      x-data:
        additionalProperties:
          type: string
```
